### ISSUE TITLE
PyPi & conda-forge packaging

### ISSUE THREAD

**Issue by IAlibay** [OpenFreeEnergy/konnektor#78]
We should make a v0.1 release and relelase on pypi & conda-forge

**Comment by IAlibay** [comment]
@RiesBen you'll need to add Mike and I to the Konnektor PyPi maintenance team.

**Comment by IAlibay** [comment]
Or maybe just conda-forge because of openff-models.

**Comment by RiesBen** [comment]
> @RiesBen you'll need to add Mike and I to the Konnektor PyPi maintenance team.

this did already happen :)

**Comment by mikemhenry** [comment]
I can make a release, what commit is v0.1?

**Comment by mikemhenry** [comment]
Also at a quick glance, it looks like the CI failure is a real failure.

**Comment by RiesBen** [comment]
> Also at a quick glance, it looks like the CI failure is a real failure.

Hi, could solve that crash
